Write-Output "" 
Write-Output "" 
Write-Output "" 
Write-Output "   __ _ _          ___                         "
Write-Output "  / /(_) | _____  / _ \__ _ _ __ ___  ___ _ __ "
Write-Output " / / | | |/ / _ \/ /_)/ _' | '__/ __|/ _ \ '__|"
Write-Output "/ /__| |   <  __/ ___/ (_| | |  \__ \  __/ |   "   
Write-Output "\____/_|_|\_\___\/    \__,_|_|  |___/\___|_|   "
Write-Output ""
Write-Output "      GitHub.com/securityjoes/LikeParser"
Write-Output "             Author: Eilay Yosfan"
Write-Output "                 Version: 2.1"
Write-Output ""  